version: '2.1'
services:

  db:
    image: mysql:latest
    container_name: rfef-db
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: carlosbouzas
      MYSQL_DATABASE: rfefdb
      MYSQL_USER: carlosbouzas
      MYSQL_PASSWORD: carlosbouzas
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 15s
      timeout: 20s
      retries: 10
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - rfefnetwork

  web:
    build: .
    container_name: rfef-web
    ports:
      - 8080:9000
    depends_on:
      db:
          condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://rfef-db:3306/rfefdb?allowPublicKeyRetrieval=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: carlosbouzas
        SPRING_DATASOURCE_PASSWORD: carlosbouzas
    networks:
      - rfefnetwork

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - rfefnetwork


networks:
  rfefnetwork:

volumes:
  init: